name: Code Review
on: pull_request

jobs:
  review_job:
    name: Review Job
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.x'
          
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install transformers torch requests

        - name: Load Review Prompt
          id: load_prompt
          run: |
            PROMPT=$(cat review_prompt.md)
            echo "::set-output name=prompt::$PROMPT"

        - name: Extract pull request diff
          id: get_diff
          run: |
            DIFF=$(git diff origin/develop...HEAD)
            echo "::set-output name=diff::$DIFF"

        - name: Run Code Review with Hugging Face Model
          id: review_code
          run: |
            from transformers import pipeline

            # 경량 모델 불러오기
            review_model = pipeline("text-generation", model="Qwen/Qwen2.5-Coder-7B-Instruct")

            # Pull request의 코드 diff 가져오기
            diff = "${{ steps.get_diff.outputs.diff }}"

            # 코드 리뷰 생성
            review_prompt = f"Review the following code changes and provide feedback:\n\n{diff}"
            review_comment = review_model(review_prompt, max_length=500, num_return_sequences=1)[0]['generated_text']

            # 리뷰 코멘트 파일에 저장
            with open("review_comment.txt", "w") as file:
                file.write(review_comment)

      - name: Add comment to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('review_comment.txt', 'utf-8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            })
