name: Code Review
on: pull_request

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          # Remove unnecessary large packages
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk mongodb-org
          sudo apt-get autoremove -y
          sudo apt-get clean
          
          # Remove large directories we won't need
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          
          # Show available space
          df -h

      - uses: actions/checkout@v4
      
      - name: Get PR Diff
        id: get_diff
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          DIFF=$(gh pr diff $PR_NUMBER)
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Review Prompt
        id: load_prompt
        run: |
          echo "prompt<<EOF" >> $GITHUB_OUTPUT
          cat review_prompt.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install only required dependencies with minimal extras
          pip install --no-cache-dir transformers torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir requests

      - name: Run Code Review with Hugging Face Model
        id: review_code
        run: |
          python3 << 'EOL'
          from transformers import pipeline
          import os
          import torch
          
          # Clear CUDA cache if available
          if torch.cuda.is_available():
              torch.cuda.empty_cache()
          
          prompt = os.getenv('PROMPT_CONTENT')
          diff = os.getenv('DIFF_CONTENT')
          
          # Initialize model with CPU and low precision
          review_model = pipeline(
              "text-generation", 
              model="Qwen/Qwen2.5-Coder-7B-Instruct",
              device_map="cpu",
              torch_dtype=torch.float32
          )
          
          full_prompt = f"{prompt}\n```\n{diff}\n```"
          review_comment = review_model(
              full_prompt,
              max_length=2000,
              num_return_sequences=1,
              temperature=0.7
          )[0]['generated_text']
          
          with open("review_comment.txt", "w") as file:
              file.write(review_comment)
              
          # Clear memory
          del review_model
          if torch.cuda.is_available():
              torch.cuda.empty_cache()
          EOL
        env:
          PROMPT_CONTENT: ${{ steps.load_prompt.outputs.prompt }}
          DIFF_CONTENT: ${{ steps.get_diff.outputs.diff }}

      - name: Add comment to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('review_comment.txt', 'utf-8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            })
