name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        run: |
          # Check if Python 3.10 is already installed
          if ! command -v python3.10 &> /dev/null; then
            brew update
            brew install python@3.10
            echo 'export PATH="/usr/local/opt/python@3.10/bin:$PATH"' >> ~/.bash_profile
            source ~/.bash_profile
          fi
          python3.10 --version

      - name: Install dependencies
        run: |
          pip3 -m pip install --upgrade pip
          pip3 install transformers torch

      - name: Run AI Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pip3 .github/scripts/ai_code_review.py

# End of file. No additional code.
