name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: self-hosted
    
    env:
      HF_HOME: ${{ github.workspace }}/.cache/huggingface
      PYTHONPATH: ${{ github.workspace }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Explicitly specify Python 3.10 path and create virtual environment
      - name: Set up Python environment
        run: |
          # Create virtual environment using Python 3.10
          /usr/local/opt/python@3.10/bin/python3.10 -m venv ${{ github.workspace }}/.venv
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH
          
          # Activate virtual environment
          source ${{ github.workspace }}/.venv/bin/activate
          
          # Print Python version for verification
          python --version
          
          # Upgrade pip
          python -m pip install --upgrade pip
          
          # Install PyTorch and other dependencies
          pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
          pip3 install transformers accelerate PyGithub
        
      - name: Cache HuggingFace models
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/huggingface
          key: huggingface-${{ runner.os }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            huggingface-${{ runner.os }}-
            
      - name: Create necessary directories
        run: |
          mkdir -p ${{ github.workspace }}/.cache/huggingface
          mkdir -p ${{ github.workspace }}/.github/scripts
          mkdir -p ${{ github.workspace }}/.github/templates
          
      - name: Get changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ' ')" >> $GITHUB_ENV
          
      - name: Generate code review
        run: |
          source ${{ github.workspace }}/.venv/bin/activate
          python .github/scripts/generate_review.py \
            --model "Qwen/Qwen2.5-Coder-7B-Instruct" \
            --prompt-template ".github/templates/review_prompt.md" \
            --output-template ".github/templates/review_format.md" \
            --files "$CHANGED_FILES"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
