name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: self-hosted
    
    env:
      HF_HOME: ~/.cache/huggingface  # Cache directory for models
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get the changed files
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Cache HuggingFace models
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: huggingface-${{ runner.os }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            huggingface-${{ runner.os }}-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers accelerate
          
      - name: Get changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ' ')" >> $GITHUB_ENV
          
      - name: Generate code review
        run: |
          python .github/scripts/generate_review.py \
            --model "Qwen/Qwen2.5-Coder-7B-Instruct" \
            --prompt-template ".github/templates/ui_review.md" \
            --output-template ".github/templates/review_format.md" \
            --files "$CHANGED_FILES"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
