name: Code Review
on: pull_request
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers torch requests

      - name: Load Review Prompt
        id: load_prompt
        run: |
          PROMPT=$(cat << 'EOF'
          $(cat review_prompt.md)
          EOF
          )
          echo "prompt<<EOF" >> $GITHUB_OUTPUT
          echo "$PROMPT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Extract pull request diff
        id: get_diff
        run: |
          DIFF=$(git diff origin/develop...HEAD)
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Code Review with Hugging Face Model
        id: review_code
        run: |
          python3 << 'EOL'
          from transformers import pipeline
          import os
          
          # Initialize the model
          review_model = pipeline("text-generation", model="Qwen/Qwen2.5-Coder-7B-Instruct")
          
          # Get the prompt and diff from previous steps
          with open(os.environ['GITHUB_OUTPUT'], 'r') as f:
              content = f.read()
              prompt = "${{ steps.load_prompt.outputs.prompt }}"
              diff = "${{ steps.get_diff.outputs.diff }}"
          
          # Combine prompt and diff
          full_prompt = f"{prompt}\n\nCode to Review:\n```\n{diff}\n```"
          
          # Generate review
          review_comment = review_model(
              full_prompt,
              max_length=2000,
              num_return_sequences=1,
              temperature=0.7
          )[0]['generated_text']
          
          # Save review
          with open("review_comment.txt", "w") as file:
              file.write(review_comment)
          EOL

      - name: Add comment to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('review_comment.txt', 'utf-8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            })
