name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'

      - name: Set permissions
        run: |
          sudo mkdir -p /Users/runner/hostedtoolcache
          sudo chown -R $USER:$USER /Users/runner/hostedtoolcache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers torch

      - name: Run AI Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/ai_code_review.py

# End of file. No additional code.
